### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by danielbayley** [azer/title-from-url#1]
@azer I read [about you pulling all your stuff](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.hppqt9ejo), including this module off npm. This has eventually broken one of my Atom packages, but I noticed at the end you put:

> if you volunteer to take ownership of any module in my Github, I’ll happily transfer the ownership.

I had an idea for this module before I found yours, so I would happily take this off your hands if you like?

**Comment by azer** [comment]
yeah, I'm adding you as owner to this repo

**Comment by danielbayley** [comment]
@azer Ok, cool. I accepted as far as I can tell… but nothing seems to have happened?

**Comment by azer** [comment]
@danielbayley you're also owner in the repo now. you can contact NPM and re-publish it.

**Comment by danielbayley** [comment]
@azer Cheers. Although nothing appears to have changed. Am I missing something?

**Comment by danielbayley** [comment]
@azer I just looked here https://help.github.com/articles/about-repository-transfers and noticed it said:

> If the new owner doesn't accept the transfer within one day, it won't complete.

So I'm pretty sure that's what has happened. Sorry, but maybe try transfer again, and I'll make sure I find the email faster this time 😄

**Comment by danielbayley** [comment]
@azer This didn't go through in the end… any chance you could re-transfer?

**Comment by danielbayley** [comment]
@azer Hey man, this didn't go through in the end… any chance you could re-transfer? I want to push an update to my Atom package that uses this…
